from enum import Enum


class ElewiseType(Enum):
    ELEWISE_UNDEFINED = 0
    ELEWISE_CAST = 1
    ELEWISE_MULS = 2
    ELEWISE_COS = 3
    ELEWISE_SIN = 4
    ELEWISE_NEG = 5
    ELEWISE_QUANT = 6
    ELEWISE_LOGICAL_NOT = 7
    ELEWISE_ADD = 8
    ELEWISE_MUL = 9
    ELEWISE_REALDIV = 10
    ELEWISE_LOGICAL_AND = 11
    ELEWISE_LOGICAL_OR = 12
    ELEWISE_LESS = -13
    ELEWISE_GREATER = 14
    ELEWISE_SUB = 15
    ELEWISE_TANH = 16
    ELEWISE_EQUAL = 17
    ELEWISE_QUANT_PER_CHANNEL = 18
    ELEWISE_DEQUANT_PER_CHANNEL = 19
    ELEWISE_DYNAMIC_QUANT = 20
